USE [master]
GO

/****** Object:  Database [JobPortal]    Script Date: 5.03.2021 20:43:50 ******/
CREATE DATABASE [JobPortal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JobPortal', FILENAME = N'C:\Users\talha\JobPortal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JobPortal_log', FILENAME = N'C:\Users\talha\JobPortal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JobPortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JobPortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JobPortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JobPortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JobPortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JobPortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [JobPortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JobPortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JobPortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JobPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JobPortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JobPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JobPortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JobPortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JobPortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JobPortal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JobPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JobPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JobPortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JobPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JobPortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JobPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JobPortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JobPortal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [JobPortal] SET  MULTI_USER 
GO

ALTER DATABASE [JobPortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JobPortal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JobPortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JobPortal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JobPortal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JobPortal] SET QUERY_STORE = OFF
GO

USE [JobPortal]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [JobPortal] SET  READ_WRITE 
GO

